### ISSUE TITLE
ply文件查看异常，缺少list

### ISSUE THREAD

**Issue by wing158** [hbb1/2d-gaussian-splatting#6] opened 2024-05-06 20:53 UTC
https://playcanvas.com/model-viewer 
![errMsg](https://github.com/hbb1/2d-gaussian-splatting/assets/29857187/fa3713df-2968-4470-9ce8-d11c4bf8cf11)

常用的元象 3dgs 导入工具也提示 list异常，可否解决下？
![errmsg2](https://github.com/hbb1/2d-gaussian-splatting/assets/29857187/f3215e6f-caa6-43cf-8d38-4a4971ba5b84)

**Comment by hbb1** [comment] 2024-05-07 03:44
Unfortunately, there is not an online viewer. Close as it is a duplicate of issue #4

**Closed by hbb1** 2024-05-07 03:44 UTC
